/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'liguofeng' at '17/02/27 23:00' with Gradle 2.14.1
 *
 * @author liguofeng, @date 17/02/27 23:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
